In [1]:
import inspect

## NumPy とは
---
多次元配列の演算、特に線形代数などの科学計算の基本的な機能を提供。

## NumPy の使い方

### インポート
---
慣習として`np`という名前をつける。

In [2]:
import numpy as np

### 配列の作成
---
`numpy.array`に Python の配列を渡す。

In [3]:
np.array??

In [4]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

連続する整数の配列は`numpy.arange`を使用する。

In [5]:
np.arange??

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### 練習問題

10 から 49 までの整数が並んだベクトル (1 次元配列) を作成 ([100 numpy exercises #7](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb))

ある区間を等間隔に分割した配列を作成するには`numpy.linspace`を使用する。

In [7]:
np.linspace??

In [8]:
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

初期値 0 の配列を作成するには`numpy.zeros`を使用する。

In [9]:
np.zeros??

In [10]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

###### 練習問題

0が10個並んだベクトルを作成 ([100 numpy exercises #3](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb))

初期値 1 の配列を作成するには`numpy.ones`を使用する。

In [11]:
np.ones??

In [12]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

任意の初期値で埋められた配列を作成するには`numpy.full`を使用する。

In [13]:
np.full??

In [14]:
np.full((2, 3), 4)

array([[4, 4, 4],
       [4, 4, 4]])

`numpy.*_like`で既存の配列と同じサイズの配列を作成可能。

In [15]:
[f[0] for f in inspect.getmembers(np, inspect.isfunction) if f[0].endswith('_like')]

['full_like', 'ones_like', 'zeros_like']

In [16]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6]])
z = np.zeros_like(m)
z

array([[0, 0, 0],
       [0, 0, 0]])

### 配列の操作
---
基本的には Python の配列と同様の方法で値の変更やスライシングが可能。

In [17]:
a = np.arange(5)
a[2] = 9
a

array([0, 1, 9, 3, 4])

In [18]:
a[-2:]

array([3, 4])

###### 練習問題

0 が 10 個並んだベクトルを作成し、 5 番目の要素を 1 にする ([100 numpy exercises #6](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb))

###### 練習問題

ベクトル要素の順番を逆にする ([100 numpy exercises #8](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb))

2 行 3 列目の値を指定するには以下のように行う。

In [19]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6]])
m[1, 2]

6

行単位や列単位でも指定可能。

In [20]:
m[1]

array([4, 5, 6])

In [21]:
m[:, 2]

array([3, 6])

###### 練習問題

10x10 の外周の数値が 1 で内側の数値が 0 の行列を作成 ([100 numpy exercises #15](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb))

$$
\left(\begin{matrix}
    1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1
\end{matrix}\right)
$$

行列 (2 次元配列) の転置 (行と列の入れ替え) は T 属性で取得可能。

In [22]:
m.T

array([[1, 4],
       [2, 5],
       [3, 6]])

配列のサイズは shape 属性で取得可能。

In [23]:
m.shape

(2, 3)

配列のサイズ変更は`numpy.reshape`を使用する。

In [24]:
np.reshape??

In [25]:
m.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

配列の要素数は size 属性で取得可能。

In [26]:
m.size

6

###### 練習問題

0 から 8 までの整数が並んだ 3x3 行列を作成 ([100 numpy exercises #9](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb))

### 要素同士の演算
---
同じサイズの配列同士なら、その要素同士の演算は通常の演算子で可能。

In [27]:
a = np.arange(6).reshape((2, 3))
b = np.arange(4, 10).reshape((2, 3))
print('a=')
print(a)
print('b=')
print(b)

a=
[[0 1 2]
 [3 4 5]]
b=
[[4 5 6]
 [7 8 9]]


In [28]:
a + b

array([[ 4,  6,  8],
       [10, 12, 14]])

In [29]:
a * b

array([[ 0,  5, 12],
       [21, 32, 45]])