In [1]:
import numpy as np

## pandasとは
---
データフレームという表計算ソフトのような構造とデータ分析のための機能を提供。

## pandasの使い方

### インポート
---
慣習として`pd`という名前をつける。

In [2]:
import pandas as pd

### データフレームの作成
---
`pandas.DataFrame`に配列や辞書型のオブジェクトを渡す。

In [3]:
np.random.seed(1234)
length = 4
a = np.arange(length)
b = np.arange(length) * 2
c = np.arange(length) + length
data = np.random.randint(0, 9, (length, 3))
print(f'a={a}')
print(f'b={b}')
print(f'c={c}')
print('data=')
print(data)

a=[0 1 2 3]
b=[0 2 4 6]
c=[4 5 6 7]
data=
[[3 6 5]
 [4 8 1]
 [7 6 8]
 [0 5 0]]


In [4]:
pd.DataFrame??

In [5]:
pd.DataFrame(data)

0  1  2
0  3  6  5
1  4  8  1
2  7  6  8
3  0  5  0

In [6]:
pd.DataFrame(dict(A=a, B=b))

A  B
0  0  0
1  1  2
2  2  4
3  3  6

### 行・列の名前変更
---
データフレームの`columns`属性や`index`属性に配列で指定可能。

In [7]:
df = pd.DataFrame(data)
df.columns = ['列A', '列B', '列C']
df.index = ['行1', '行2', '行3', '行4']
df

列A  列B  列C
行1   3   6   5
行2   4   8   1
行3   7   6   8
行4   0   5   0

データフレームを作成する際にも指定可能。

In [8]:
pd.DataFrame(data, index=['行1', '行2', '行3', '行4'], columns=['列A', '列B', '列C'])

列A  列B  列C
行1   3   6   5
行2   4   8   1
行3   7   6   8
行4   0   5   0

### 要素の取得
---
列名を指定して、各列を取得可能。

In [9]:
df['列A']

行1    3
行2    4
行3    7
行4    0
Name: 列A, dtype: int64

In [10]:
df[['列A', '列C']]

列A  列C
行1   3   5
行2   4   1
行3   7   8
行4   0   0

データフレームの各列は`pandas.Series`オブジェクト。  
`pandas.DataFrame`で利用可能な関数の多くは`pandas.Series`でも利用可能。

In [11]:
type(df['列A'])

pandas.core.series.Series

`loc`を使用すると行名や列名でデータを取得可能。  
スライシングも利用可能。

In [12]:
df.loc['行1']

列A    3
列B    6
列C    5
Name: 行1, dtype: int64

In [13]:
df.loc['行2', '列A']

4

In [14]:
df.loc[:, ['列A', '列C']]

列A  列C
行1   3   5
行2   4   1
行3   7   8
行4   0   0

In [15]:
df.loc['行2':, '列B']

行2    8
行3    6
行4    5
Name: 列B, dtype: int64

`iloc`を使用すると行番号や列番号でデータを取得可能。  
`loc`と同様にスライシングも利用可能。

In [16]:
df.iloc[0]

列A    3
列B    6
列C    5
Name: 行1, dtype: int64

In [17]:
df.iloc[1, 0]

4

In [18]:
df.iloc[:, [0, 2]]

列A  列C
行1   3   5
行2   4   1
行3   7   8
行4   0   0

In [19]:
df.iloc[1:, 1]

行2    8
行3    6
行4    5
Name: 列B, dtype: int64